### PR TITLE
Update koa-joi-router to 4.0.0

### PR DESCRIPTION
**Pull request by miserylee**
Add new output structure support.
Add nested structure (Object, Array) support.
Add default, tests, valids, invalids, examples to paramsTable
Change font-family of panel-table to code style (for more clear reading)
Change example

### CODE REVIEW

**Comment by miserylee** [comment]
Here is the preview.

image

**Comment by miserylee** [comment]
#4

**Comment by a-s-o** [comment]
Hey thanks for the contribution; I have not tested it yet but I will publish it to npm as 2.x so you can use it right away. Version 1.x can be used with the old joi router

I will also add you as a contributor; thanks again

**Comment by miserylee** [comment]
@a-s-o  It's nice! I will update the readme in my free time~😝

**Pull request merged**
