### PR TITLE
exact versions in package.json, fix require for lodash/get

### PR DESCRIPTION
**Pull request by kevinludwig**
fix for issue #2

### CODE REVIEW

**Comment by yagarasu** [comment]
Hey! Thanks for this fix. Confirmed, it solves the issue.
We are also having problems with this. Fortunately it's an easy fix to implement by hand. Let's hope @a-s-o  accepts the pull request soon.

**Comment by a-s-o** [comment]
Thanks for the PR. Sorry for the delay...I hadnt run into the issue and did not notice the open request until @yagarsu commented

**Comment by yagarasu** [comment]
Thanks, @a-s-o . Great tool, btw ;)

**Comment by pedroposada** [comment]
Hi @a-s-o , thanks very much for this fix, can you create a tag for the latest version? Is this how npm can publish the latest version?

**Comment by a-s-o** [comment]
Yup, will publish to npm later today. Along with some other much needed love for this package (i.e. option to hide handler code from docs).

**Comment by kevinludwig** [comment]
Hi @a-s-o, can you have a look at issue #4 and see if you think it'd be easy to patch?

**Comment by a-s-o** [comment]
@pedroposada released to npm with v0.9.0. Thanks for the input

**Pull request merged**
